spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
  datasource:
    url: jdbc:postgresql://localhost:5432/whatachad # TODO : 테스트와 배포 환경에서 profile 분리
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create # test 환경에서만 쓸 것
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /index.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 3000

