# default 공통 설정
spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop # TODO : test 환경에서만 쓸 것
--- # local 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/whatachad
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
--- # dev 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://whatachad-db-instance.cw81y2eduyhn.ap-northeast-2.rds.amazonaws.com:5432/whatachad
    driver-class-name: org.postgresql.Driver
    username: jinhyeon
    password: gEKaLnEX6oqt3jSZ8Vvq